(in-package #:cl-glfw3-kit)

(define-condition cl-glfw3-kit-error (error) ()
  (:documentation "Base condition for errors signalled by this library."))

(defmacro define-glfw-error-condition (name)
  "Define NAME as a CL-GLFW3-KIT-ERROR subtype with a description slot."
  (let ((reader (intern (format nil "~A-DESCRIPTION" name))))
    `(define-condition ,name (cl-glfw3-kit-error)
       ((description :initarg :description :initform "" :reader ,reader))
       (:report (lambda (condition stream)
                  (format stream "~(~A~): ~A" ',name (,reader condition)))))))

(define-glfw-error-condition glfw-not-initialized)
(define-glfw-error-condition glfw-no-current-context)
(define-glfw-error-condition glfw-invalid-enum)
(define-glfw-error-condition glfw-invalid-value)
(define-glfw-error-condition glfw-out-of-memory)
(define-glfw-error-condition glfw-api-unavailable)
(define-glfw-error-condition glfw-version-unavailable)
(define-glfw-error-condition glfw-platform-error)
(define-glfw-error-condition glfw-format-unavailable)
(define-glfw-error-condition glfw-no-window-context)
(define-glfw-error-condition glfw-cursor-unavailable)
(define-glfw-error-condition glfw-feature-unavailable)
(define-glfw-error-condition glfw-feature-unimplemented)
(define-glfw-error-condition glfw-platform-unavailable)

(define-condition glfw-unknown-error (cl-glfw3-kit-error)
  ((code :initarg :code :initform 0 :reader glfw-unknown-error-code)
   (description :initarg :description :initform "" :reader glfw-unknown-error-description))
  (:report (lambda (condition stream)
             (format stream "Unrecognized GLFW error ~D: ~A"
                     (glfw-unknown-error-code condition)
                     (glfw-unknown-error-description condition))))
  (:documentation "Signaled for an error code absent from *GLFW-ERROR-CONDITIONS*."))
